project_id = "ntxtymwpxhuajbedcqyv"

[functions.group-chat]
verify_jwt = false

[functions.extract-id]
verify_jwt = false

[functions.search-trip]
verify_jwt = false

[functions.reverse-geocode]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.find-alternative-activity]
verify_jwt = false

[functions.generate-share-image]
verify_jwt = false
